---
language: python

dist: 'trusty'

services:
  - docker

addons:
  apt:
    packages:
      - gnupg2

python:
  - "2.7"
  - "3.6"

env:
  - LINTREVIEW_SETTINGS="./settings.py" GOPATH="${TRAVIS_BUILD_DIR}/gocode"

before_install:
  - make images

install:
  - pip install -r requirements-dev.txt
  - pip install .
  # Sample config file
  - cp settings.sample.py settings.py

script:
  - >
    pytest -p no:cacheprovider
      --requires_linters
      --cov=lintreview
      --cov-report=xml:/data/results/coverage.xml
      --junitxml=/data/results/nosetests.xml

after_success:
  - codecov

notifications:
  email:
    on_failure: change
